"""add_subscription_tier_to_users

Revision ID: dbdc769c3583
Revises: 47c7d5c24347
Create Date: 2026-10-01 16:23:29.292673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdc769c3583'
down_revision = '47c7d5c24347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
